In [1]:
import numpy as np

In [72]:
n_examples = 2
n_classes = 10

In [73]:
y2_cap = np.random.randn(n_examples, n_classes)

In [74]:
y2_cap.shape

(2, 10)

In [75]:
exponents = np.exp(y2_cap - np.max(y2_cap))
y2_cap_softmax = exponents / (np.sum(exponents))

In [76]:
y2_cap_softmax

array([[0.01435404, 0.0285987 , 0.0278682 , 0.00279488, 0.12187904,
        0.01633921, 0.07578386, 0.0114579 , 0.05598773, 0.01438927],
       [0.03083385, 0.07949121, 0.06419838, 0.07925507, 0.2331755 ,
        0.01447734, 0.01070684, 0.07061817, 0.00874103, 0.03904978]])

In [104]:
y = np.array(range(n_examples))
y = y.reshape(1, n_examples)

In [105]:
y.shape

(1, 2)

In [106]:
y

array([[0, 1]])

In [107]:
y2_cap_softmax.shape

(2, 10)

In [108]:
y2_cap_softmax[0]

array([0.01435404, 0.0285987 , 0.0278682 , 0.00279488, 0.12187904,
       0.01633921, 0.07578386, 0.0114579 , 0.05598773, 0.01438927])

In [109]:
m = y.shape[0]

In [125]:
log_likelihood = -np.log(y2_cap_softmax[range(m), y])

In [111]:
y2_cap_softmax

array([[0.01435404, 0.0285987 , 0.0278682 , 0.00279488, 0.12187904,
        0.01633921, 0.07578386, 0.0114579 , 0.05598773, 0.01438927],
       [0.03083385, 0.07949121, 0.06419838, 0.07925507, 0.2331755 ,
        0.01447734, 0.01070684, 0.07061817, 0.00874103, 0.03904978]])

In [120]:
m

1

In [119]:
[list(range(m))]

[[0]]

In [124]:
y

array([[0, 1]])

In [123]:
y2_cap_softmax[range(2), y]

array([[0.01435404, 0.07949121]])

In [112]:
y

array([[0, 1]])

In [113]:
y2_cap_softmax[range(m), y]

array([[0.01435404, 0.0285987 ]])

In [56]:
y2_cap_softmax[range(m), y].shape

(9, 9)

In [52]:
log_likelihood

array([[5.33289539, 6.42062604, 6.32607411, 5.20201027, 4.86370973,
        3.89355982, 5.86923594, 5.04684617, 6.12305448],
       [4.86651006, 2.85931297, 4.68627059, 6.19747676, 6.15880816,
        6.85169258, 6.86275533, 5.56998578, 8.29570999],
       [6.11103261, 3.64050205, 4.76067144, 7.62736586, 4.26702564,
        5.84368942, 5.30381765, 3.56374432, 4.56630533],
       [4.13444575, 3.66500196, 6.84767667, 4.70970245, 4.71221612,
        5.54901906, 4.34326789, 6.88009665, 5.41667853],
       [5.01851844, 3.00888072, 4.86824123, 3.96918701, 2.89131905,
        5.14911288, 4.98336785, 5.45800918, 4.10194162],
       [5.31471164, 3.44577043, 7.30614604, 6.15855046, 5.23635321,
        3.58056082, 5.61523499, 5.69132191, 5.87605222],
       [3.49595774, 5.40977476, 6.7639385 , 4.33700815, 5.30311209,
        4.37953262, 5.08297148, 5.9169563 , 3.12052791],
       [5.01075488, 4.37229107, 5.48671571, 4.43789649, 2.88454231,
        3.19117865, 5.357994  , 6.08027722, 5.67926722],


In [53]:
loss = np.sum(log_likelihood) / m

In [54]:
loss

45.628099542475375

In [ ]:
raw_x_train, raw_x_test = x_mnist_train, x_mnist_test
x_mnist_train, x_mnist_test = np.expand_dims(raw_x_train, axis=1), np.expand_dims(raw_x_test, axis=1)
x_mnist_train = x_mnist_train / 255
x_mnist_test = x_mnist_test / 255
x_mnist_train.max()
x_mnist_train.shape
np.unique(y_mnist_train[:5000], return_counts=True)
sequential_model.reset_params()
sequential_model.train([x_mnist_train[:5000], y_mnist_train[:5000]], [x_mnist_test[:5000], y_mnist_test[:5000]], epochs=5, learning_rate=1e-02, debug=True, batch_size=8)

In [ ]:
# import mnist
# # mnist.init()
# x_mnist_train, y_mnist_train, x_mnist_test, y_mnist_test = mnist.load()

# x_mnist_train, x_mnist_test = x_mnist_train.reshape((x_mnist_train.shape[0],28, 28)), x_mnist_test.reshape((x_mnist_test.shape[0], 28, 28))